name: Testing stuff

on:
  push:
    branches:
      - main


jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: check skip
        run: |
          SKIP_DEPLOY="false"
          if echo '${{ toJson(github.event.commits.*.message) }}' | grep -q '#skip'; then
            SKIP_DEPLOY="true"
          fi
          echo "SKIP_DEPLOY=$SKIP_DEPLOY" >> $GITHUB_ENV
          echo "SKIP_DEPLOY: $SKIP_DEPLOY"